### ISSUE TITLE
Grove vision ai news

### ISSUE THREAD

**Issue by Pillar1989** [taunoe/grove-vision-ai#3]
Hi @taunoe It's great to see your project, and I'm glad our products were able to help you.
We've refactored the software on Grove Vision AI with the new Edgelab and especially the newly launched FOMOv2, which allows you to reach 10fs object detection capability on Grove Vision AI and hopefully inspire you even more.
https://github.com/Seeed-Studio/EdgeLab
https://github.com/Seeed-Studio/edgelab-model-zoo
https://github.com/Seeed-Studio/edgelab-example-vision-ai

**Comment by taunoe** [comment]
I will definitely look and experiment with these all-new things!
